-- 어울림 마음쉼터 — 게시판/신청곡 Supabase 테이블 (v2)
-- 실행: Supabase Dashboard → SQL Editor → 붙여넣고 Run
-- 효과: 게시판 글이 모든 방문자에게 공유됩니다

-- 1) 마음 게시판
create table if not exists dungji_board (
  id bigint generated by default as identity primary key,
  nick text,
  text text not null,
  secret boolean default false,
  owner_key text,
  warm int default 0,
  cheer int default 0,             -- 힘내요 (v2)
  react_voters text[] default '{}',  -- 따뜻해요+힘내요 중복방지
  created_at timestamptz default now()
);

-- 2) 신청곡
create table if not exists dungji_songs (
  id bigint generated by default as identity primary key,
  title text not null,
  why text,
  created_at timestamptz default now()
);

-- 3) RLS — 익명 사이트 정책 (누구나 읽기/쓰기, 반응 갱신 허용)
alter table dungji_board enable row level security;
alter table dungji_songs enable row level security;

drop policy if exists "board_read" on dungji_board;
create policy "board_read" on dungji_board for select using (true);
drop policy if exists "board_insert" on dungji_board;
create policy "board_insert" on dungji_board for insert with check (true);
drop policy if exists "board_update" on dungji_board;
create policy "board_update" on dungji_board for update using (true) with check (true);

drop policy if exists "songs_read" on dungji_songs;
create policy "songs_read" on dungji_songs for select using (true);
drop policy if exists "songs_insert" on dungji_songs;
create policy "songs_insert" on dungji_songs for insert with check (true);

-- 4) 비밀글 서버 필터링 뷰 (내용=null 마스킹)
create or replace view dungji_board_public as
  select id, nick, case when secret then null else text end as text,
         secret, owner_key, warm, cheer, react_voters, created_at
  from dungji_board;
